

mybatis:
  type-aliases-package: com.ibo.medical_platform.entity
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 12345
spring:
  application:
    name: medical-platform
  profiles:
    active: dev
  http:
    encoding:
      charset: utf-8
      enabled: true